name: github-actions

on:
    push:

jobs:
    test:
        name: test
        runs-on: ubuntu-20.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: get path
              run: |
                echo $GITHUB_WORKSPACE
            - name: create docker container
              run: |
                  docker-compose -f docker-compose-github-actions.yml build
                  docker-compose -f docker-compose-github-actions.yml up -d
            - name: start docker container
              run: |
                  docker-compose -f docker-compose-github-actions.yml start