name: github-actions

on:
    push:

jobs:
    test:
        name: test
        runs-on: ubuntu-20.04
        timeout-minutes: 3
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: docker compose build
              run: |
                  docker-compose -f docker-compose-github-actions.yml build
            - name: docker compose up
              run: |
                  docker-compose -f docker-compose-github-actions.yml up -d
            - name: python container start
              run: |
                docker-compose -f docker-compose-github-actions.yml start