name: github-actions

on:
    push:

jobs:
    test:
        name: test
        runs-on: ubuntu-20.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: get path
              run: |
                echo $GITHUB_WORKSPACE
            - name: create docker container
              run: |
                  make setup
            - name: start docker container
              run: |
                  make start
            - name: enter docker python container
              run: |
                  docker-compose exec --user root -T python bash
            
            - name: run python file
              run: |
                echo $GITHUB_WORKSPACE
                python3 main.py