name: github-actions

on:
    push:

jobs:
    test:
        name: test
        runs-on: ubuntu-20.04
        timeout-minutes: 3
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: Run docker-compose up
              run: |
                docker-compose -f docker-compose-github-actions.yml up --build --exit-code-from python
            - if: success()
              run: echo success
            - if: failure()
              run: echo failure