name: github-actions

on:
    push:

jobs:
    test:
        name: test
        runs-on: ubuntu-20.04
        timeout-minutes: 3
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: get path
              run: |
                echo $GITHUB_WORKSPACE
            - name: docker compose run
              run: |
                  docker-compose -f docker-compose-github-actions.yml up --build
            - name: docker compose run
              run: |
                  docker-compose -f docker-compose-github-actions.yml down