name: Test

on:
    push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.9.18'
            - name: Create docker containers
              run: |
                docker-compose build
                docker-compose up -d
            
            - name: Enter python container
              run: |
                pip list

            - name: Run python file
              run: |
                cd app/
                pip install --upgrade pip
                pip install selenium==4.0.0
                python main.py
            